# Generated by Django 4.2.23 on 2026-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('graduate_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'member_info',
            },
        ),
    ]
