# Generated by Django 4.2.23 on 2026-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_memberinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='consent_recruitment',
            field=models.BooleanField(default=False),
        ),
    ]
