# Generated by Django 4.2.23 on 2026-05-10 13:52

from django.db import migrations, models
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentpost_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentpost',
            name='short_id',
            field=models.CharField(db_index=True, default=recruitment.models.generate_short_uuid, editable=False, max_length=8, unique=True),
        ),
    ]
