# Generated by Django 4.2.23 on 2026-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruitmentpost_short_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_bank_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.TextField()),
                ('job_link', models.URLField()),
                ('job_show', models.BooleanField(default=False)),
            ],
        ),
    ]
