# Generated by Django 4.2.23 on 2026-05-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_job_bank_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_bank_link',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='job_bank_link',
            name='recruitment_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='job_bank_links', to='recruitment.recruitmentpost'),
            preserve_default=False,
        ),
    ]
