# Generated by Django 4.2.23 on 2026-06-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=50)),
                ('session_yearmonth', models.IntegerField()),
                ('session_is_active', models.BooleanField(default=True)),
                ('session_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('item_diacode', models.CharField(help_text='品項代碼，主鍵', max_length=10, primary_key=True, serialize=False)),
                ('item_english_name', models.CharField(help_text='英文商品名', max_length=50)),
                ('item_chinese_name', models.CharField(help_text='中文商品名', max_length=50)),
                ('item_chemical_name', models.CharField(help_text='學名', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(help_text='盤點者帳號，用於登陸用', max_length=20, primary_key=True, serialize=False)),
                ('user_id2', models.CharField(blank=True, help_text='第二帳號，當環境可能同時擁有多個帳號的時候', max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, help_text='姓名', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NeedInventoryMonth',
            fields=[
                ('nim_id', models.AutoField(help_text='序號，自動ID', primary_key=True, serialize=False)),
                ('nim_diacode', models.ForeignKey(help_text='品項代碼', on_delete=django.db.models.deletion.PROTECT, related_name='diacode_month', to='inventory.iteminfo')),
                ('nim_yearmonth', models.ForeignKey(help_text='盤點活動', on_delete=django.db.models.deletion.PROTECT, related_name='session_month', to='inventory.inventorysession')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSite',
            fields=[
                ('is_id', models.AutoField(help_text='序號，自動ID', primary_key=True, serialize=False)),
                ('is_site', models.CharField(help_text='櫃位', max_length=10)),
                ('is_diacode', models.ForeignKey(help_text='品項代碼', on_delete=django.db.models.deletion.PROTECT, related_name='diacode_site', to='inventory.iteminfo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPackage',
            fields=[
                ('ip_id', models.AutoField(help_text='序號，自動ID', primary_key=True, serialize=False)),
                ('ip_package_name', models.IntegerField(choices=[(1, '排'), (2, '盒'), (3, '箱')], help_text='包裝名稱，如：排、盒、箱')),
                ('ip_package_count', models.IntegerField(help_text='單位數量，如：一排14顆，輸入14')),
                ('ip_diacode', models.ForeignKey(help_text='品項代碼', on_delete=django.db.models.deletion.PROTECT, related_name='diacode_package', to='inventory.iteminfo')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRocord',
            fields=[
                ('ir_id', models.AutoField(help_text='序號，自動ID', primary_key=True, serialize=False)),
                ('ir_site', models.CharField(blank=True, help_text='櫃位，由哪個櫃位盤點到，也可能是空白', max_length=10)),
                ('ir_count', models.DecimalField(decimal_places=2, help_text='盤點量，接受半顆或1/4顆', max_digits=8)),
                ('ir_datetime', models.DateTimeField(auto_now_add=True, help_text='盤點資料輸入時間，前台送出時間')),
                ('ir_diacode', models.ForeignKey(help_text='品項代碼', on_delete=django.db.models.deletion.PROTECT, related_name='diacode_record', to='inventory.iteminfo')),
                ('ir_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_session', to='inventory.inventorysession')),
                ('ir_user', models.ForeignKey(help_text='盤點者', on_delete=django.db.models.deletion.PROTECT, related_name='record_user', to='inventory.userinfo')),
            ],
        ),
    ]
