# Generated by Django 4.2.23 on 2026-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysession',
            name='session_created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='盤點活動創造日期'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='session_id',
            field=models.AutoField(help_text='序號，自動ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='session_is_active',
            field=models.BooleanField(default=True, help_text='活動是否啟用'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='session_name',
            field=models.CharField(help_text='盤點活動名稱，建議輸入民國年月，方便辨識，如：115年6月', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='session_yearmonth',
            field=models.IntegerField(help_text='盤點年月，民國年，EX：11501'),
        ),
    ]
