# Generated by Django 4.2.23 on 2026-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_memberinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
