# Generated by Django 4.2.23 on 2026-04-15 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_memberinfo_line_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
