# Generated by Django 4.2.23 on 2026-05-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_memberinfo_consent_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='live_site',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
