# Generated by Django 4.2.23 on 2026-05-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_memberinfo_live_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.memberinfo')),
            ],
            options={
                'db_table': 'recruitment_event',
            },
        ),
    ]
