# Generated by Django 4.2.23 on 2026-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_recruitmentevent'),
    ]

    operations = [
        migrations.RemoveField(
        model_name="recruitmentevent",
        name="event_date",
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='event_date',
            field=models.DateField(),
        ),
    ]
