# Generated by Django 4.2.23 on 2026-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_recruitmentevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='have_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='note',
            field=models.CharField(blank=True),
        ),
    ]
